from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

build = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'BSMD1812-300', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BSMD1812-300'}), 'ref_prefix':'F', 'fplist':None, 'footprint':'Fuse:Fuse_1812_4532Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'AO3401A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AO3401A'}), 'ref_prefix':'Q', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT),
            Pin(num='2',name='S',func=pin_types.PASSIVE),
            Pin(num='3',name='D',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SS34', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SS34'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SMA', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE),
            Pin(num='2',name='A',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'AP2112K-3.3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP2112K-3.3'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='EN',func=pin_types.INPUT),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT)] }),
        Part(**{ 'name':'RP2040', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'RP2040'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:QFN-56-1EP_7x7mm_P0.4mm_EP3.2x3.2mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='IOVDD',func=pin_types.PWRIN),
            Pin(num='2',name='GPIO0',func=pin_types.BIDIR),
            Pin(num='3',name='GPIO1',func=pin_types.BIDIR),
            Pin(num='4',name='GPIO2',func=pin_types.BIDIR),
            Pin(num='5',name='GPIO3',func=pin_types.BIDIR),
            Pin(num='6',name='GPIO4',func=pin_types.BIDIR),
            Pin(num='7',name='GPIO5',func=pin_types.BIDIR),
            Pin(num='8',name='GPIO6',func=pin_types.BIDIR),
            Pin(num='9',name='GPIO7',func=pin_types.BIDIR),
            Pin(num='10',name='IOVDD',func=pin_types.PWRIN),
            Pin(num='11',name='GPIO8',func=pin_types.BIDIR),
            Pin(num='12',name='GPIO9',func=pin_types.BIDIR),
            Pin(num='13',name='GPIO10',func=pin_types.BIDIR),
            Pin(num='14',name='GPIO11',func=pin_types.BIDIR),
            Pin(num='15',name='GPIO12',func=pin_types.BIDIR),
            Pin(num='16',name='GPIO13',func=pin_types.BIDIR),
            Pin(num='17',name='GPIO14',func=pin_types.BIDIR),
            Pin(num='18',name='GPIO15',func=pin_types.BIDIR),
            Pin(num='19',name='TESTEN',func=pin_types.INPUT),
            Pin(num='20',name='XIN',func=pin_types.INPUT),
            Pin(num='21',name='XOUT',func=pin_types.OUTPUT),
            Pin(num='22',name='IOVDD',func=pin_types.PWRIN),
            Pin(num='23',name='DVDD',func=pin_types.PWRIN),
            Pin(num='24',name='SWCLK',func=pin_types.INPUT),
            Pin(num='25',name='SWDIO',func=pin_types.BIDIR),
            Pin(num='26',name='RUN',func=pin_types.INPUT),
            Pin(num='27',name='GPIO16',func=pin_types.BIDIR),
            Pin(num='28',name='GPIO17',func=pin_types.BIDIR),
            Pin(num='29',name='GPIO18',func=pin_types.BIDIR),
            Pin(num='30',name='GPIO19',func=pin_types.BIDIR),
            Pin(num='31',name='GPIO20',func=pin_types.BIDIR),
            Pin(num='32',name='GPIO21',func=pin_types.BIDIR),
            Pin(num='33',name='IOVDD',func=pin_types.PWRIN),
            Pin(num='34',name='GPIO22',func=pin_types.BIDIR),
            Pin(num='35',name='GPIO23',func=pin_types.BIDIR),
            Pin(num='36',name='GPIO24',func=pin_types.BIDIR),
            Pin(num='37',name='GPIO25',func=pin_types.BIDIR),
            Pin(num='38',name='GPIO26_ADC0',func=pin_types.BIDIR),
            Pin(num='39',name='GPIO27_ADC1',func=pin_types.BIDIR),
            Pin(num='40',name='GPIO28_ADC2',func=pin_types.BIDIR),
            Pin(num='41',name='GPIO29_ADC3',func=pin_types.BIDIR),
            Pin(num='42',name='IOVDD',func=pin_types.PWRIN),
            Pin(num='43',name='ADC_AVDD',func=pin_types.PWRIN),
            Pin(num='44',name='VREG_VIN',func=pin_types.PWRIN),
            Pin(num='45',name='VREG_VOUT',func=pin_types.PWROUT),
            Pin(num='46',name='USB_DM',func=pin_types.BIDIR),
            Pin(num='47',name='USB_DP',func=pin_types.BIDIR),
            Pin(num='48',name='USB_VDD',func=pin_types.PWRIN),
            Pin(num='49',name='IOVDD',func=pin_types.PWRIN),
            Pin(num='50',name='DVDD',func=pin_types.PWRIN),
            Pin(num='51',name='QSPI_SD3',func=pin_types.BIDIR),
            Pin(num='52',name='QSPI_SCLK',func=pin_types.OUTPUT),
            Pin(num='53',name='QSPI_SD0',func=pin_types.BIDIR),
            Pin(num='54',name='QSPI_SD2',func=pin_types.BIDIR),
            Pin(num='55',name='QSPI_SD1',func=pin_types.BIDIR),
            Pin(num='56',name='QSPI_SS_N',func=pin_types.OUTPUT),
            Pin(num='57',name='GND',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'W25Q128JVSIQ', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'W25Q128JVSIQ'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-8_5.3x5.3mm_P1.27mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='CS_N',func=pin_types.INPUT),
            Pin(num='2',name='DO_IO1',func=pin_types.BIDIR),
            Pin(num='3',name='WP_IO2',func=pin_types.BIDIR),
            Pin(num='4',name='GND',func=pin_types.PWRIN),
            Pin(num='5',name='DI_IO0',func=pin_types.BIDIR),
            Pin(num='6',name='CLK',func=pin_types.INPUT),
            Pin(num='7',name='HOLD_IO3',func=pin_types.BIDIR),
            Pin(num='8',name='VCC',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'ABM8-272-T3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ABM8-272-T3'}), 'ref_prefix':'Y', 'fplist':None, 'footprint':'Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='X1',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='X2',func=pin_types.PASSIVE),
            Pin(num='4',name='GND',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'TS-1187A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TS-1187A'}), 'ref_prefix':'SW', 'fplist':None, 'footprint':'wigglecam:SW_TS-1187A_5.1x5.1mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE),
            Pin(num='2',name='A2',func=pin_types.PASSIVE),
            Pin(num='3',name='B',func=pin_types.PASSIVE),
            Pin(num='4',name='B2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SWD', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SWD'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='SWCLK',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PASSIVE),
            Pin(num='3',name='SWDIO',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'TYPE-C-31-M-12', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TYPE-C-31-M-12'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_USB:USB_C_Receptacle_HRO_TYPE-C-31-M-12', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='A1',name='GND',func=pin_types.PWRIN),
            Pin(num='A12',name='GND',func=pin_types.PWRIN),
            Pin(num='A4',name='VBUS',func=pin_types.PWRIN),
            Pin(num='A9',name='VBUS',func=pin_types.PWRIN),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR),
            Pin(num='A6',name='DP1',func=pin_types.BIDIR),
            Pin(num='A7',name='DM1',func=pin_types.BIDIR),
            Pin(num='A8',name='SBU1',func=pin_types.NOCONNECT),
            Pin(num='B1',name='GND',func=pin_types.PWRIN),
            Pin(num='B12',name='GND',func=pin_types.PWRIN),
            Pin(num='B4',name='VBUS',func=pin_types.PWRIN),
            Pin(num='B9',name='VBUS',func=pin_types.PWRIN),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR),
            Pin(num='B6',name='DP2',func=pin_types.BIDIR),
            Pin(num='B7',name='DM2',func=pin_types.BIDIR),
            Pin(num='B8',name='SBU2',func=pin_types.NOCONNECT),
            Pin(num='SH',name='SHIELD',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'USBLC6-2SC6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USBLC6-2SC6'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='IO1',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='IO2',func=pin_types.PASSIVE),
            Pin(num='4',name='IO2B',func=pin_types.PASSIVE),
            Pin(num='5',name='VBUS',func=pin_types.PWRIN),
            Pin(num='6',name='IO1B',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'LM358DR2G', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LM358DR2G'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='OUT1',func=pin_types.OUTPUT),
            Pin(num='2',name='IN1-',func=pin_types.INPUT),
            Pin(num='3',name='IN1+',func=pin_types.INPUT),
            Pin(num='4',name='V-',func=pin_types.PWRIN),
            Pin(num='5',name='IN2+',func=pin_types.INPUT),
            Pin(num='6',name='IN2-',func=pin_types.INPUT),
            Pin(num='7',name='OUT2',func=pin_types.OUTPUT),
            Pin(num='8',name='V+',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'AO3400A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AO3400A'}), 'ref_prefix':'Q', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT),
            Pin(num='2',name='S',func=pin_types.PASSIVE),
            Pin(num='3',name='D',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'LED1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED1'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_JST:JST_XH_B2B-XH-A_1x02_P2.50mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'LED2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED2'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_JST:JST_XH_B2B-XH-A_1x02_P2.50mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'INA219AIDCNR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'INA219AIDCNR'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-8', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='IN+',func=pin_types.PASSIVE),
            Pin(num='2',name='IN-',func=pin_types.PASSIVE),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='VS',func=pin_types.PWRIN),
            Pin(num='5',name='SCL',func=pin_types.BIDIR),
            Pin(num='6',name='SDA',func=pin_types.BIDIR),
            Pin(num='7',name='A0',func=pin_types.INPUT),
            Pin(num='8',name='A1',func=pin_types.INPUT)] }),
        Part(**{ 'name':'R_shunt', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R_shunt'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'Resistor_SMD:R_2512_6332Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'VBAT_IN', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'VBAT_IN'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_JST:JST_XH_B2B-XH-A_1x02_P2.50mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'VBAT_OUT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'VBAT_OUT'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_JST:JST_XH_B2B-XH-A_1x02_P2.50mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SHUTTER', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SHUTTER'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_JST:JST_XH_B2B-XH-A_1x02_P2.50mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'PESD5V0S1BA', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PESD5V0S1BA'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-323', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE),
            Pin(num='2',name='A',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'EC11E18244AU', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'EC11E18244AU'}), 'ref_prefix':'SW', 'fplist':None, 'footprint':'Rotary_Encoder:RotaryEncoder_Alps_EC11E-Switch_Vertical_H20mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='A',name='A',func=pin_types.PASSIVE),
            Pin(num='B',name='B',func=pin_types.PASSIVE),
            Pin(num='C',name='COM',func=pin_types.PASSIVE),
            Pin(num='S1',name='SW1',func=pin_types.PASSIVE),
            Pin(num='S2',name='SW2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'WS2812B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'WS2812B'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'LED_SMD:LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='DOUT',func=pin_types.OUTPUT),
            Pin(num='3',name='VSS',func=pin_types.PWRIN),
            Pin(num='4',name='DIN',func=pin_types.INPUT)] }),
        Part(**{ 'name':'1N4148W', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'1N4148W'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-123', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE),
            Pin(num='2',name='A',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'LED_GREEN', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED_GREEN'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE),
            Pin(num='2',name='A',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'PI_HEADER_2x6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PI_HEADER_2x6'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_PinSocket_2.54mm:PinSocket_2x06_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='P1',func=pin_types.PASSIVE),
            Pin(num='2',name='P2',func=pin_types.PASSIVE),
            Pin(num='3',name='P3',func=pin_types.PASSIVE),
            Pin(num='4',name='P4',func=pin_types.PASSIVE),
            Pin(num='5',name='P5',func=pin_types.PASSIVE),
            Pin(num='6',name='P6',func=pin_types.PASSIVE),
            Pin(num='7',name='P7',func=pin_types.PASSIVE),
            Pin(num='8',name='P8',func=pin_types.PASSIVE),
            Pin(num='9',name='P9',func=pin_types.PASSIVE),
            Pin(num='10',name='P10',func=pin_types.PASSIVE),
            Pin(num='11',name='P11',func=pin_types.PASSIVE),
            Pin(num='12',name='P12',func=pin_types.PASSIVE)] })])