"""Extract the enclosure-relevant mechanical data from the routed
board and write enclosure/board_dims.scad — so the CAD is generated
from the same source of truth as the fab outputs and can never drift
from the PCB.

Board-local coordinates: origin at the PCB's top-left corner, x right,
y DOWN (KiCad convention). The SCAD flips y where needed.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import pcbnew
from kicad_common import BOARD_PATH, BOARD_H, BOARD_W, to_local

OUT = Path(__file__).resolve().parents[2] / "enclosure" / "board_dims.scad"


def main():
    b = pcbnew.LoadBoard(str(BOARD_PATH))
    fps = {f.GetReference(): f for f in b.GetFootprints()}

    holes = []
    for ref in ("H1", "H2", "H3", "H4"):
        holes.append(to_local(fps[ref].GetPosition()))

    # EC11: footprint origin sits at the A/B/C pad column; the shaft
    # axis is at origin + (7.5, 2.5) (measured from the footprint
    # source in hardware/scripts history)
    enc = to_local(fps["SW3"].GetPosition())
    enc_shaft = (enc[0] + 7.5, enc[1] + 2.5)

    usb = to_local(fps["J2"].GetPosition())
    ws = to_local(fps["D4"].GetPosition())
    sw1 = to_local(fps["SW1"].GetPosition())
    sw2 = to_local(fps["SW2"].GetPosition())
    swd = to_local(fps["J1"].GetPosition())
    jsts = {r: to_local(fps[r].GetPosition())
            for r in ("J3", "J4", "J5", "J6", "J7")}
    hdr = to_local(fps["J8"].GetPosition())

    def v2(name, p):
        return f"{name} = [{p[0]:.2f}, {p[1]:.2f}];"

    lines = [
        "// GENERATED by hardware/scripts/08_enclosure_dims.py from",
        "// hardware/kicad/wigglecam.kicad_pcb — do not edit by hand.",
        "// Board-local mm, origin top-left, y DOWN (KiCad convention).",
        "",
        f"pcb_w = {BOARD_W};",
        f"pcb_h = {BOARD_H};",
        "pcb_t = 1.6;",
        "",
        "// M2.5 mounting holes",
        "pcb_holes = [" + ", ".join(
            f"[{x:.2f}, {y:.2f}]" for x, y in holes) + "];",
        "",
        "// EC11 encoder: 7 mm threaded bushing on the shaft axis,",
        "// body height above PCB ~6.5 mm, shaft H20 variant",
        v2("enc_shaft", enc_shaft),
        "enc_bush_d = 7.2;   // clearance for the M7 bushing",
        "enc_body_h = 6.5;",
        "",
        "// USB-C receptacle, mouth out the bottom (y = pcb_h) edge",
        v2("usbc_center", usb),
        "usbc_w = 9.6;  usbc_h = 3.6;   // cutout incl. clearance",
        "",
        "// WS2812B status LED (5x5) — light pipe location",
        v2("ws2812", ws),
        "",
        "// BOOTSEL / RUN tact switches (actuator ~1.5 mm above body)",
        v2("btn_bootsel", sw1),
        v2("btn_run", sw2),
        "",
        "// SWD header (internal, no cutout needed)",
        v2("swd", swd),
        "",
        "// JST-XH connectors (cable exits)",
        v2("jst_led1", jsts["J3"]),
        v2("jst_led2", jsts["J4"]),
        v2("jst_vbat_in", jsts["J5"]),
        v2("jst_vbat_out", jsts["J6"]),
        v2("jst_shutter", jsts["J7"]),
        "",
        "// Pi-interface 2x6 header (ribbon inside the enclosure)",
        v2("pi_header", hdr),
        "",
        "// tallest component: JST-XH housings ~7.0 mm; keep >=4 mm",
        "// clearance above them",
        "pcb_max_comp_h = 7.0;",
        "pcb_leg_h = 2.0;   // THT legs below the PCB",
    ]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
